# Generated by Django 5.1 on 2025-09-01 20:27

import django.db.models.deletion
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('telefone', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Telefone')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='aplicacao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.cliente')),
                ('produto', models.ManyToManyField(through='aplicacao.ItemVenda', to='aplicacao.produto')),
            ],
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.venda'),
        ),
    ]
