# Generated by Django 5.1 on 2025-09-08 20:25

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_cliente_alter_produto_qtd_itemvenda_perfil_venda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='endereco',
        ),
        migrations.AddField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=localflavor.br.models.BRStateField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
